name: CI

on:
  pull_request:
    types: [opened, synchronize]

# Ensure one run job at a time
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  ci-go:
    uses: thienchuong/reusable-workflows/.github/workflows/ci-go.yml@v6
    with:
      docker-registry: xxx.dkr.ecr.ap-southeast-1.amazonaws.com
      sonar-project: podinfo
      sonar-coverage-path: output/cover.out
    secrets: inherit
